### ISSUE TITLE
Dead code

### ISSUE THREAD

**Issue by Masynchin** [BobaUbisoft17/Aiogram_calendar#1]
https://github.com/BobaUbisoft17/Aiogram_calendar/blob/70373ae6da2bd8ecdb8f79f5ffe47de010222672/bot.py#L62-L65

This code doesn't do anything useful and it should be removed.

**Comment by Masynchin** [comment]
@BobaUbisoft17 what would you do in order to prevent this from happening again?

**Comment by BobaUbisoft17** [comment]
Finally started using flake8
